name: instagram_clone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.3
  velocity_x: ^3.5.1
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: InstagramIcons
      fonts:
        - asset: assets/fonts/InstagramIcons.ttf

    - family: sf-pro
      fonts:
        - asset: assets/fonts/sf-pro.ttf

  assets:
    - "assets/images/."
