// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqxgqsRTVatY-UV06NppU0xJ8Bh29yp_4',
    appId: '1:263937942079:web:48ad519ff73269b7e7ce8a',
    messagingSenderId: '263937942079',
    projectId: 'instagram-clone-c97df',
    authDomain: 'instagram-clone-c97df.firebaseapp.com',
    storageBucket: 'instagram-clone-c97df.appspot.com',
    measurementId: 'G-KEGG4M44T6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl6xXZItsOLUyVfatsyJzjNhgr1IGsnl4',
    appId: '1:263937942079:android:2f43d011c0093f4fe7ce8a',
    messagingSenderId: '263937942079',
    projectId: 'instagram-clone-c97df',
    storageBucket: 'instagram-clone-c97df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy6Lt1I1q8RsRQ-U1YmQwh6bkU83Atc8Y',
    appId: '1:263937942079:ios:e27355b5f65968ece7ce8a',
    messagingSenderId: '263937942079',
    projectId: 'instagram-clone-c97df',
    storageBucket: 'instagram-clone-c97df.appspot.com',
    iosBundleId: 'com.inhrithikmishra.instagramclone.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy6Lt1I1q8RsRQ-U1YmQwh6bkU83Atc8Y',
    appId: '1:263937942079:ios:e27355b5f65968ece7ce8a',
    messagingSenderId: '263937942079',
    projectId: 'instagram-clone-c97df',
    storageBucket: 'instagram-clone-c97df.appspot.com',
    iosBundleId: 'com.inhrithikmishra.instagramclone.instagramClone',
  );
}
